server:
  port: '${BACKEND_PORT:8005}'
  servlet:
    context-path: '/api'
  compression:
    enabled: true
  address: 0.0.0.0


spring:

  datasource:
    driver-class-name: 'org.postgresql.Driver'

    url: '${DATABASE_URL:jdbc:postgresql://localhost:5433/postgres}'
    username: '${DATABASE_USERNAME:postgres}'
    password: '${DATABASE_PASSWORD:147258}'
    hikari:
      maximum-pool-size: 25